name: phat_dart_cli
version: 0.8.0
description: >-
  The purpose of this tool is to let an individual enter text and have a hashed
  output to use as the password to the site or program. Initially the program
  will hash the input in SHA 256 and output in hexadecimal. THe plans for this
  program are to allow the selection of three different SHA lengths (256, 384,
  and 512). Also, the output numbering system will be selectable between
  hexadecimal, base64, and base58. Also, the number of digits in the ouput
  will be selectable in case a site can only have a certain number of digits
  in a password. THe last step will be for the output to be copied to the
  clipboard so if can be pasted into the program or site.
environment:
  sdk: '>=2.0.0 <3.0.0'
dependencies:
  crypto: ^2.1.4
  convert: ^2.1.1
  fast_base58: ^0.1.8

